title: Web Novel Theme!
email: your-email@example.com
description: >- 
  a place to display your web novel
tagline: >-
  The home of your web novel
baseurl: "/"
url: "example.com"

twitter:
  username: example
  card: summary

twitter_username: codekarmadev
github_username: CodeKarmaDev

theme: 'web_novel'



novel:
  title: "The Upper Crust"
  author: "John Doe"
  copyright:
    short: >-
      **The Upper Crust, Vol 1**

      by **John Doe**

      Copyright &copy; 2022 Example, JJI

    warning: >-
      PIRATING CONTENT IS ILLEGAL

    long: 'COPYRIGHT.md'



collections:
  chapters:
    sort_by: chapter
    output: true
    # permalink: /chapters/:num/


plugins:
  - jekyll-feed
  - jekyll-seo-tag



sass:
  load_paths:
    - _sass
    - node_modules
  style: compressed

exclude:
  - graphics
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package-lock.json
  - package.json
  - web_novel.gemspec
  - lib

