title: Web Novel Theme!
email: your-email@example.com
description: >- 
  a place to display your web novel
tagline: >-
  The home of your web novel
baseurl: "/"
url: "example.com"

twitter:
  username: example
  card: summary

twitter_username: example
github_username: example

theme: 'jekyll-web-novel'

use_netlify_cms: false

novel:
  title: "The Upper Crust"
  author: "John Doe"
  lang: en
  start_chapter: 1
  copyright:
    short: >-
      **The Upper Crust, Vol 1**

      by **John Doe**

      Copyright &copy; 2022 Example, JJI

    warning: >-
      PIRATING CONTENT IS ILLEGAL

    long: 'COPYRIGHT.md'



collections:
  chapters:
    sort_by: chapter
    output: true
    permalink: /:collection/:path/
  tabs:
    sort_by: order
    output: true


defaults:
  - scope:
      path: "_chapters/*"
    values:
      layout: "chapter"
      type: 'chapters'
      published: true
  - scope:
      path: "_tabs/*"
    values:
      layout: "page"
      type: 'tabs'

plugins:
  - jekyll-feed
  - jekyll-seo-tag


sass:
  load_paths:
    - _sass
    - node_modules
  style: compressed

feed:
  collections:
    - chapters

exclude:
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - package-lock.json
  - package.json
  - jekyll-web-novel.gemspec
  - lib

