# config.yml
# Optional config for netlifyCMS

backend:
  name: git-gateway
  branch: netlify
  # ^ push changes to the netlify branch instead of master
  # so I can review and merge the changes in before they go live.
media_folder: 'assets/uploads'
public_folder: "/assets/uploads"
# publish_mode: editorial_workflow
# ^ Creates new a pull request for every new change 'published'
site_url: https://example.com

collections:
  - name: tabs
    label: 'Pages'
    folder: '_tabs/'
    create: false
    slug: "{{slug}}"
    summery: "{{title}}"
    editor:
      preview: false
    fields: 
      - { label: 'Title', name: "title", widget: 'string' }
      - { label: 'Published', name: 'published', widget: 'boolean', default: true, required: false }
      - { label: 'Permalink', name: "permalink", widget: 'string', default: '/:basename/', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: chapters
    label: 'Chapters'
    folder: '_chapters/'
    create: false
    slug: "{{slug}}"
    summery: "{{field.volume}}.{{field.chapter}} {{title}}"
    editor:
      preview: false
    fields: 
      - { label: 'Title', name: "title", widget: 'string' }
      - { label: 'Published', name: 'published', widget: 'boolean', default: true, required: false }
      - { label: 'Chapter', name: "chapter", widget: 'number', default: 01, value_type: 'int' }
      - { label: 'Volume', name: "volume", widget: 'number', default: 01, value_type: 'int' }
      - { label: 'Permalink', name: "permalink", widget: 'string', default: '/:basename/', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: previews
    label: 'Previews'
    folder: '_previews/'
    create: false
    slug: "{{slug}}"
    summery: "{{field.volume}}.{{field.chapter}} {{title}} - preview"
    editor:
      preview: false
    fields: 
      - { label: 'Title', name: "title", widget: 'string' }
      - { label: 'Published', name: 'published', widget: 'boolean', default: false, required: false }
      - { label: 'Chapter', name: "chapter", widget: 'number', default: 01, value_type: 'int' }
      - { label: 'Volume', name: "volume", widget: 'number', default: 01, value_type: 'int' }
      - { label: 'Permalink', name: "permalink", widget: 'string', default: '/:basename/', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
