#!/usr/bin/env ruby

STDOUT.sync = true

gem_dir = File.expand_path("..",File.dirname(__FILE__))
$LOAD_PATH.unshift gem_dir # Look in gem directory for resources first.

require 'fileutils'

class WebNovelInit

    def initialize
        cp_folder('_boilerplates')
        cp_folder('pages')
        FileUtils.mkpath('_includes')
        FileUtils.mkpath('_chapters')
        FileUtils.mkpath('_previews')
        FileUtils.mkpath('_volumes')
        cp_file('_includes/copyright.md')
        cp_file('_config.yml')
        puts 'Remember to remove `index.markdown`, `404.html`, and `about.md`'
        puts 'You can use the _boilerplates provided with the `jekyll-page-boilerplate` gem.'
        puts '`$ bplate volume vol=01 -T "Water"`'
        puts '`$ bplate chapter vol=01 cht=01 -T "My First Chapter"`'
        puts '`$ bplate preview vol=01 cht=02 -T "Secret Chapter for Proofreading"`'
        puts 'Web Novel jekyll template files created.'
    end
    
    def cp_folder(folder)
        FileUtils.cp_r(File.join(__dir__,'../', folder), folder)
    end

    def cp_file(file)
        FileUtils.cp(File.join(__dir__,'../', file), file)
    end
end

WebNovelInit.new
